package component: router;

interface router-api {
  variant action {
    register(string),
    follow(u64),
    unfollow(u64),
    post-tweet(string),
  }

  enum query-type {
    user-profile,
    user-followers,
    user-following,
    user-tweets,
    user-timeline,
  }

  record user-profile {
    user-id: u64,
    username: string,
    followers: list<u64>,
    following: list<u64>,
  }

  record tweet {
    tweet-id: u64,
    author-id: u64,
    content: string,
    timestamp: s64,
  }

  record tweet-data {
    user-id: u64,
    tweets: list<tweet>,
  }

  record timeline-data {
    author-id: u64,
    tweet: tweet,
  }

  variant router-action-response {
    success,
    failure(string),
  }

  variant router-query-response {
    user-profile-response(user-profile),
    user-followers-response(list<u64>),
    user-following-response(list<u64>),
    user-tweets-response(tweet-data),
    user-timeline-response(list<timeline-data>),
    failure(string),
  }

  // Route actions to appropriate workers based on consistent hashing or other criteria
  route-action: func(action: action, user-id: u64) -> router-action-response; // response

  // Route queries to appropriate workers based on consistent hashing or other criteria
  route-query: func(query-type: query-type, user-id: u64) -> router-query-response; // response
}

world router {
  import component: user-management-stub/stub-user-management;
  import component: tweet-management-stub/stub-tweet-management;
  import component: timeline-management-stub/stub-timeline-management;

  export router-api;
}
