[package]
name = "golem-x"
version = "2.1.0"
edition = "2021"

[package.metadata.component.target]
path = "wit"

[dependencies]
chrono = "0.4.39"
wit-bindgen-rt = { version = "0.40.0", features = ["bitflags"] }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
required-features = []

[profile.release]
opt-level = "s"
debug = false
lto = true
strip = true
