[workspace]
members = ["user_management", "tweet_management", "timeline_management", "worker_management", "user_management-stub", "tweet_management-stub", "timeline_management-stub", "worker_management-stub"]
resolver = "2"

[profile.release]
opt-level = "s"
debug = false
lto = true
strip = true
