[config]
default_to_workspace = false

[tasks.add-stub-dependency-timeline-management-router]
args = ["stubgen", "add-stub-dependency", "--stub-wit-root", "timeline-management-stub/wit", "--dest-wit-root", "router/wit", "--overwrite", "--update-cargo-toml"]
command = "golem-cli"
cwd = "."
dependencies = ["generate-timeline-management-stub"]

[tasks.add-stub-dependency-tweet-management-router]
args = ["stubgen", "add-stub-dependency", "--stub-wit-root", "tweet-management-stub/wit", "--dest-wit-root", "router/wit", "--overwrite", "--update-cargo-toml"]
command = "golem-cli"
cwd = "."
dependencies = ["generate-tweet-management-stub"]

[tasks.add-stub-dependency-user-management-router]
args = ["stubgen", "add-stub-dependency", "--stub-wit-root", "user-management-stub/wit", "--dest-wit-root", "router/wit", "--overwrite", "--update-cargo-toml"]
command = "golem-cli"
cwd = "."
dependencies = ["generate-user-management-stub"]

[tasks.build]
args = ["build"]
command = "cargo-component"
dependencies = ["clean", "regenerate-stubs"]

[tasks.build-flow]
dependencies = ["build", "post-build"]

[tasks.build-release]
args = ["build", "--release"]
command = "cargo-component"
dependencies = ["clean", "regenerate-stubs"]

[tasks.clean]
args = ["clean"]
command = "cargo-component"

[tasks.compose-release-router]
args = ["stubgen", "compose", "--source-wasm", "target/wasm32-wasip1/release/router.wasm", "--stub-wasm", "target/wasm32-wasip1/release/user_management_stub.wasm", "--stub-wasm", "target/wasm32-wasip1/release/tweet_management_stub.wasm", "--stub-wasm", "target/wasm32-wasip1/release/timeline_management_stub.wasm", "--dest-wasm", "target/wasm32-wasip1/release/router_composed.wasm"]
command = "golem-cli"
cwd = "."

[tasks.compose-router]
args = ["stubgen", "compose", "--source-wasm", "target/wasm32-wasip1/debug/router.wasm", "--stub-wasm", "target/wasm32-wasip1/debug/user_management_stub.wasm", "--stub-wasm", "target/wasm32-wasip1/debug/tweet_management_stub.wasm", "--stub-wasm", "target/wasm32-wasip1/debug/timeline_management_stub.wasm", "--dest-wasm", "target/wasm32-wasip1/debug/router_composed.wasm"]
command = "golem-cli"
cwd = "."

[tasks.default]
alias = "build"

[tasks.generate-timeline-management-stub]
args = ["stubgen", "generate", "-s", "timeline-management/wit", "-d", "timeline-management-stub"]
command = "golem-cli"
cwd = "."

[tasks.generate-tweet-management-stub]
args = ["stubgen", "generate", "-s", "tweet-management/wit", "-d", "tweet-management-stub"]
command = "golem-cli"
cwd = "."

[tasks.generate-user-management-stub]
args = ["stubgen", "generate", "-s", "user-management/wit", "-d", "user-management-stub"]
command = "golem-cli"
cwd = "."

[tasks.post-build]
dependencies = ["compose-router"]

[tasks.post-build-release]
dependencies = ["compose-release-router"]

[tasks.regenerate-stubs]
dependencies = ["add-stub-dependency-user-management-router", "add-stub-dependency-tweet-management-router", "add-stub-dependency-timeline-management-router"]

[tasks.release-build-flow]
dependencies = ["build-release", "post-build-release"]

[tasks.test]
args = ["test"]
command = "cargo-component"
dependencies = ["clean"]
