[package]
name = "router"
version = "0.1.0"
edition = "2021"

[package.metadata.component]
package = "component:router"

[dependencies]
blake2 = "0.10.6"
url = "2.5.2"

[dependencies.wit-bindgen-rt]
version = "0.30.0"
features = ["bitflags"]

[lib]
crate-type = ["cdylib"]
required-features = []
