package component: tweet-management;

interface tweet-api {
  record posted-tweet {
    tweet-id: string,
    author-id: string,
    content: string,
    timestamp: s64,
  }

  // Post a new tweet
  post-tweet: func(user-id: string, content: string) -> result<posted-tweet>; // tweet

  // Get tweets for a specific user
  get-user-tweets: func(user-id: string) -> result<list<posted-tweet>>; // list of tweets

  // Get tweets from a list of tweet-ids
  get-specific-tweets: func(user-id: string, tweet-ids: list<string>) -> result<list<posted-tweet>>; // list of tweets
}

world tweet-management {
  export tweet-api;
}
