package component: timeline-management;

interface timeline-api {
  enum timeline-action {
    insert,
    remove,
  }

  record timeline-tweet {
    tweet-id: u64,
    author-id: u64,
    timestamp: s64,
  }

  // Update the timeline for a user when a new tweet is posted
  update-timeline: func(user-id: u64, tweet-id: u64, author-id: u64, timestamp: s64, action: timeline-action) -> result<bool>; // success

  // Get the timeline for a specific user
  get-timeline: func(user-id: u64) -> result<list<timeline-tweet>>; // list of tweet-ids
}

world timeline-management {
  export timeline-api;
}
