name: CI

on:
  push:
    tags: [ 'v*.*.*' ]
    branches: [ '**' ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-is
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Install cargo-component
        run: |
          if ! command -v cargo-component &> /dev/null
          then cargo install cargo-component
          else echo "cargo-component is already installed"
          fi
      - name: Install cargo-make
        run: |
          if ! command -v cargo-make &> /dev/null
          then cargo install cargo-make
          else echo "cargo-make is already installed"
          fi
      - name: Install golem-cli
        run: |
          if ! command -v golem-cloud-cli &> /dev/null
          then
            apt-get update && \
            apt-get install -y --no-install-recommends protobuf-compiler && \
            cargo install --features universal golem-cloud-cli
          else echo "golem-cloud-cli is already installed"
          fi
      - name: Compile
        run: cargo make release-build-flow
      - name: Check formatting
        run: cargo fmt -- --check
      - name: Clippy
        run: cargo clippy -- -Dwarnings