name: CI

on:
  push:
    tags: [ 'v*.*.*' ]
    branches: [ '**' ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-is
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main
      - name: Install cargo-component
        run: cargo binstall --no-confirm cargo-component
      - name: Install cargo-make
        run: cargo binstall --no-confirm cargo-make
      - name: Install protobuf
        uses: arduino/setup-protoc@v3
      - name: Install golem-cli
        run: |
          if ! command -v golem-cli &> /dev/null
          then
            curl -L -o golem-cli https://github.com/golemcloud/golem/releases/latest/download/golem-cli-x86_64-unknown-linux-gnu &&
            chmod +x golem-cli &&
            sudo mv golem-cli /usr/local/bin/
          else echo "golem-cli is already installed"
          fi
      - name: Check formatting
        run: cargo fmt -- --check
      - name: Clippy
        run: cargo clippy -- -Dwarnings
      - name: Generate stubs
        run: cargo make regenerate-stubs
      - name: Compile
        run: cargo make release-build-flow